### ISSUE TITLE
Live preview doesn't work

### ISSUE THREAD

**Issue by ghost** [DerElam/inkscape-extension-playing-cards#1]
When I check the Live Preview I get this error:

    		PlayingCards.py:371: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--pageName",
		PlayingCards.py:374: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cardWidth",
		PlayingCards.py:377: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cardWidthUnit",
		PlayingCards.py:382: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cardHeight",
		PlayingCards.py:385: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cardHeightUnit",
		PlayingCards.py:390: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--bleedSize",
		PlayingCards.py:393: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--bleedSizeUnit",
		PlayingCards.py:398: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--minCardSpacing",
		PlayingCards.py:401: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--minCardSpacingUnit",
		PlayingCards.py:406: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cropMarkSpacing",
		PlayingCards.py:409: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--cropMarkSpacingUnit",
		PlayingCards.py:414: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--minFoldLineSpacing",
		PlayingCards.py:417: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--minFoldLineSpacingUnit",
		PlayingCards.py:422: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--pageMargin",
		PlayingCards.py:425: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--pageMarginUnit",
		PlayingCards.py:430: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--frameSpacing",
		PlayingCards.py:433: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--frameSpacingUnit",
		PlayingCards.py:438: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--gridSize",
		PlayingCards.py:441: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--gridSizeUnit",
		PlayingCards.py:446: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--gridAligned",
		PlayingCards.py:449: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--foldLineType",
		PlayingCards.py:453: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawGuides",
		PlayingCards.py:456: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawCards",
		PlayingCards.py:459: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawBleeds",
		PlayingCards.py:462: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawCropLines",
		PlayingCards.py:465: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawFoldLine",
		PlayingCards.py:468: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawPageMargin",
		PlayingCards.py:471: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
		self.OptionParser.add_option("--drawFrame",
		PlayingCards.py:941: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed. 
		extension.affect()
		PlayingCards.py:692: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" group = inkex.etree.SubElement(parent, "g")
		PlayingCards.py:732: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" guide = inkex.etree.SubElement(view, inkex.addNS("guide", "sodipodi"))
		PlayingCards.py:805: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "rect", attributes)
		PlayingCards.py:786: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "rect", attributes)
		PlayingCards.py:858: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "path", attributes)
		PlayingCards.py:861: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "path", attributes)
		PlayingCards.py:883: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "path", attributes)
		PlayingCards.py:886: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "path", attributes)
		PlayingCards.py:826: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "path", attributes)
		PlayingCards.py:936: DeprecationWarning: inkex.etree was removed, use "from lxml import etree" inkex.etree.SubElement(parent, "rect", attributes)

**Comment by DerElam** [comment]
Fixed in v1.3.0
